### ISSUE TITLE
create GitHub workflow require for this project

### ISSUE THREAD

**Issue by OliviaCE** [atomlang/atom#2]
hey guys so you all create a workflow require for this project??

**Comment by NukeWilliams** [comment]
that's a great idea we can wait for @krishpranav response

**Comment by OliviaCE** [comment]
ok sure

**Comment by krishpranav** [comment]
as per @OliviaCE It is a great idea but who will develop the workflow?? for this repo

**Comment by NukeWilliams** [comment]
I will do it @krishpranav

**Comment by krishpranav** [comment]
ok great

**Comment by OliviaCE** [comment]
cool
